[package]
name = "trainer"
version = "0.1.0"
edition = "2021"

[dependencies]
cozy-chess = "0.3.4"
rand = "0.8.5"
datafmt = { path = "../datafmt" }

[build-dependencies]
futhark-bindgen = { version = "0.2.8", features = ["build"] }
